# This is a basic workflow to help you get started with Actions

name: Arduino build

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh

      # Runs a set of commands using the runners shell
      - name: Install Arduino Uno core
        run:
          ./home/runner/work/lennatin/lennatin/bin/arduino-cli core update-index |
          ./home/runner/work/lennatin/lennatin/bin/arduino-cli core install arduino:avr

      - name: Compile
        run: ./home/runner/work/lennatin/lennatin/bin/arduino-cli compile --fqbn arduino:avr:uno -v
