name: AVR-C

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test & Coverage
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y libcunit1 libcunit1-dev lcov
          make coverage
        working-directory: ./test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install gcc-avr binutils-avr avr-libc
          sudo apt-get install avrdude
          make hex
